# Jekyll
theme: linkhub-jekyll-theme

# Site Configuration
name: PCA NextGen Conference 2025
tagline: 
description: Important links and info for PCA's NextGen conference
favicon: "/assets/favicon.png"
logo: ""
url: https://example.com # URL of your website
locale: en_US # The value specifies the locale in which these tags are marked up. It follows the format `language_TERRITORY`.
  # ga4: G-XXXXXXX # Google Analytics 4 measurement ID (optional). Remove it if not needed.
  # image:
  #   path: assets/images/example.jpg # Used for SEO (og:image, twitter:image)
  #   type: jpeg # File format of image. Change according to your image. Supported types: https://en.wikipedia.org/wiki/Media_type#Common_examples
  #   height: 100 # Pixels
  #   width: 100
  #   alt: logo

# Verified Badge Configuration
badge:
  enable: false # Set to 'true' or 'false' to enable / disable the badge
  icon: ri:verified-badge-fill  # Enter the icon name for the badge from Iconify Design (https://icon-sets.iconify.design/)
  color: '#dfb221'  # Define the color of the badge
 
# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"    

# Exclude
exclude: [README.md, Gemfile.lock, .jekyll-cache/, .github/, CHANGELOG.md, Gemfile, LICENSE.txt, funding.yml, linkhub-jekyll-theme.gemspec]
